export interface IActionTypes {

}

export const ActionTypes: any = {
    SET_ALL_PRODUCTS: 'SET_ALL_PRODUCTS',
    SET_PRODUCTS: 'SET_PRODUCTS',
    REMOVE_PRODUCTS: 'REMOVE_PRODUCTS',
    SET_PRODUCT_INFO: 'SET_PRODUCT_INFO',
    REMOVE_PRODUCT_INFO: 'REMOVE_PRODUCT_INFO',
    ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
    SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
    SET_FILTERED: 'SET_FILTERED',
    SET_IS_LOADING: 'SET_IS_LOADING',
    REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES',
    ADD_TO_BASKET: 'ADD_TO_BASKET',
    REMOVE_FROM_BASKET: 'REMOVE_FROM_BASKET'
}